
FROM openjdk:11-jre-slim
WORKDIR /usr/src
ENV MONGO_URI mongodb://localhost:27017/mydemo
ADD ./target/product_catalog_service-0.0.1-SNAPSHOT.jar /usr/src/product_catalog_service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar", "product_catalog_service-0.0.1-SNAPSHOT.jar"]