FROM openjdk:11.0.11-jre-slim
WORKDIR / usr/src
ENV MYSQL_URI MYSQL_URI:jdbc:mysql://localhost:3306/mydemo
ENV MYSQL_USERNAME root
ENV MYSQL_PASSWORD Pass@123
ADD ./target/demo-0.0.1-SNAPSHOT.jar /usr/src/demo-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar" , "demo-0.0.1-SNAPSHOT.jar"]